/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports that iskeled is up. Deliberately exposes no internal state:
         *     it is reachable without authentication so a load balancer or systemd
         *     watchdog can poll it.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The daemon is serving */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** @example 1h2m3s */
                            uptime: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build metadata of the running binary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Build metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Has this installation been set up?
         * @description The only call a client can make before signing in. It reveals nothing
         *     but whether an admin account exists, so the UI knows whether to show
         *     the bootstrap screen or the login form.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Setup state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            initialized: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first admin account
         * @description Works exactly once, while no account exists. Afterwards it answers
         *     `409 ALREADY_INITIALIZED` so a passer-by cannot claim the installation.
         *     Strictly rate limited.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Credentials"];
                };
            };
            responses: {
                /** @description The admin account was created and signed in */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description An account already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationFailed"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Strictly rate limited, and backed by a per-IP lockout after repeated
         *     failures. A wrong password and an unknown username produce the same
         *     response, and take the same time, so the endpoint cannot be used to
         *     enumerate accounts.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Credentials"];
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Invalid username or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "INVALID_CREDENTIALS",
                         *         "message": "invalid username or password"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The account is disabled */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The installation has not been set up yet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new pair
         * @description The refresh token is rotated: the presented one is revoked before the
         *     new pair is issued, so a stolen copy stops working as soon as the real
         *     user refreshes.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description A new token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                /** @description The refresh token is unknown, expired or already used */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The account is disabled */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session
         * @description Revoking an unknown token is not an error: the caller wanted to be
         *     signed out, and they are.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description The session was revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current identity and its permissions
         * @description `permissions` is what the caller's role may do; the UI uses it to hide
         *     controls rather than showing actions that will be refused.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The authenticated caller */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the Docker daemon reachable?
         * @description Always answers 200: an unreachable daemon is the answer, not a failed
         *     request. The UI polls this to drive its connection banner.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current engine reachability */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EngineStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Docker engine and host summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Engine information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemInfo"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/df": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk usage (`docker system df`) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disk usage report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiskUsage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List containers */
        get: {
            parameters: {
                query?: {
                    /** @description Include stopped containers. A bare `?all` counts as true. */
                    all?: boolean;
                    /** @description Compute `size_rw` / `size_root_fs`. Expensive on large hosts. */
                    size?: boolean;
                    /** @description Repeatable, or comma-separated. Exact `key=value` match. */
                    label?: string[];
                    /** @description Repeatable. Engine container states (running, exited, ...). */
                    status?: string[];
                    /** @description Substring match on the container name. */
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching containers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Container"][];
                            total: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        /** Inspect a container (projected) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Container detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContainerDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        /** Remove a container */
        delete: {
            parameters: {
                query?: {
                    /** @description Remove even while running. */
                    force?: boolean;
                    /** @description Also remove anonymous volumes attached to the container. */
                    volumes?: boolean;
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        /**
         * Raw engine inspect payload
         * @description The Docker Engine's own `/containers/{id}/json` response, untouched.
         *     The UI shows this in its Inspect tab, so nothing the engine reports is
         *     hidden from the operator.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Engine inspect JSON, verbatim */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a container */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ActionResult"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/stop": {
        parameters: {
            query?: {
                /**
                 * @description Seconds to wait before the engine sends SIGKILL. Omitted means the
                 *     engine's own default (10s).
                 */
                timeout?: components["parameters"]["StopTimeout"];
            };
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a container */
        post: {
            parameters: {
                query?: {
                    /**
                     * @description Seconds to wait before the engine sends SIGKILL. Omitted means the
                     *     engine's own default (10s).
                     */
                    timeout?: components["parameters"]["StopTimeout"];
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ActionResult"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/restart": {
        parameters: {
            query?: {
                /**
                 * @description Seconds to wait before the engine sends SIGKILL. Omitted means the
                 *     engine's own default (10s).
                 */
                timeout?: components["parameters"]["StopTimeout"];
            };
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart a container */
        post: {
            parameters: {
                query?: {
                    /**
                     * @description Seconds to wait before the engine sends SIGKILL. Omitted means the
                     *     engine's own default (10s).
                     */
                    timeout?: components["parameters"]["StopTimeout"];
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ActionResult"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a container
         * @description Freezes every process in the container with the cgroup freezer. The
         *     container keeps its memory and its network connections.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ActionResult"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/unpause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a paused container */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ActionResult"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/kill": {
        parameters: {
            query?: {
                /**
                 * @description Signal to send. Omitted means `SIGKILL`, which is what makes this
                 *     different from `/stop`: no grace period, no chance to shut down
                 *     cleanly.
                 */
                signal?: string;
            };
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a signal to a container */
        post: {
            parameters: {
                query?: {
                    /**
                     * @description Signal to send. Omitted means `SIGKILL`, which is what makes this
                     *     different from `/stop`: no grace period, no chance to shut down
                     *     cleanly.
                     */
                    signal?: string;
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ActionResult"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename a container */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description The new name. The engine requires
                         *     `[a-zA-Z0-9][a-zA-Z0-9_.-]+` and rejects a name already in
                         *     use.
                         * @example web-blue
                         */
                        name: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ActionResult"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/redeploy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recreate a container from a freshly pulled image
         * @description Pulls the container's image tag, then recreates the container from its
         *     existing configuration. The original is renamed out of the way rather
         *     than removed first, so a failure at any step can be rolled back: on
         *     `rolled_back: true` the original container is running again under its
         *     own name and no changes survive.
         *
         *     This is not atomic — there is a window in which neither container is
         *     serving — and it only carries over what the engine reports about the
         *     container. A container created outside iskele with options the inspect
         *     payload does not express will not reproduce them.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description The redeployment finished. Check `rolled_back` before reporting
                 *     success: a `200` with `rolled_back: true` means the new container
                 *     failed and the old one was restored.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RedeployResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["ContainerNotFound"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply one lifecycle action to several containers
         * @description Every container is attempted, whatever happens to the others: a failure
         *     halfway through a stop-everything must not leave the rest running
         *     because the loop gave up. The per-container outcome is in `results`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchRequest"];
                };
            };
            responses: {
                /** @description Every container succeeded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchResponse"];
                    };
                };
                /**
                 * @description At least one container failed. The status distinguishes "all done"
                 *     from "mostly done" without the client having to scan every result.
                 */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/ws-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a single-use ticket for a streaming channel
         * @description The ticket carries the caller's identity and permissions, is valid for
         *     60 seconds, and dies on first use. It is passed as the `ticket` query
         *     parameter to the WebSocket and SSE endpoints, which is the only place a
         *     browser can put a credential on those connections.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket issued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ticket: string;
                            /**
                             * @description Seconds until the ticket expires.
                             * @example 60
                             */
                            expires_in: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["NotInitialized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/logs": {
        parameters: {
            query: {
                /**
                 * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                 *     arrival whether or not the permission check that follows passes, so a
                 *     rejected ticket cannot be retried against another endpoint.
                 */
                ticket: components["parameters"]["StreamTicket"];
                /**
                 * @description Keep the socket open and send new lines as they arrive. Following is
                 *     the point of a WebSocket log stream, so it defaults to true;
                 *     `follow=false` asks for the backlog only.
                 */
                follow?: boolean;
                /**
                 * @description Lines of history to replay before following. Defaults to 500:
                 *     replaying a multi-gigabyte log would hang the browser.
                 */
                tail?: number;
                /** @description Include the engine's per-line timestamp. */
                timestamps?: boolean;
                /** @description Include stdout. Selecting neither stream means both. */
                stdout?: boolean;
                /** @description Include stderr. Selecting neither stream means both. */
                stderr?: boolean;
            };
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        /**
         * Stream container logs (WebSocket)
         * @description A WebSocket endpoint: send `Upgrade: websocket` and authenticate with a
         *     `ticket`. The server writes JSON text frames shaped like `LogFrame` and
         *     reads nothing; a client closing the socket stops the engine stream.
         *
         *     The handshake is rejected when `Origin` does not match `Host`, which is
         *     the only defense available here — a WebSocket is not subject to the
         *     same-origin policy the way `fetch` is.
         *
         *     Frame types: `log` for a line, `err` for a stream failure (the socket
         *     closes after it), `eof` when the container's stream ends.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                     *     arrival whether or not the permission check that follows passes, so a
                     *     rejected ticket cannot be retried against another endpoint.
                     */
                    ticket: components["parameters"]["StreamTicket"];
                    /**
                     * @description Keep the socket open and send new lines as they arrive. Following is
                     *     the point of a WebSocket log stream, so it defaults to true;
                     *     `follow=false` asks for the backlog only.
                     */
                    follow?: boolean;
                    /**
                     * @description Lines of history to replay before following. Defaults to 500:
                     *     replaying a multi-gigabyte log would hang the browser.
                     */
                    tail?: number;
                    /** @description Include the engine's per-line timestamp. */
                    timestamps?: boolean;
                    /** @description Include stdout. Selecting neither stream means both. */
                    stdout?: boolean;
                    /** @description Include stderr. Selecting neither stream means both. */
                    stderr?: boolean;
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching protocols; the log stream follows */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["TicketRejected"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/exec": {
        parameters: {
            query: {
                /**
                 * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                 *     arrival whether or not the permission check that follows passes, so a
                 *     rejected ticket cannot be retried against another endpoint.
                 */
                ticket: components["parameters"]["StreamTicket"];
                /**
                 * @description The command to run, one repeat per argument. Defaults to `/bin/sh`,
                 *     the one shell every image has.
                 */
                cmd?: string[];
                /** @description Allocate a pseudo-terminal. */
                tty?: boolean;
                /** @description Run as this user, e.g. `root` or `1000:1000`. */
                user?: string;
                /** @description Working directory inside the container. */
                workdir?: string;
                /** @description Initial terminal height. */
                rows?: number;
                /** @description Initial terminal width. */
                cols?: number;
            };
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        /**
         * Interactive exec session (WebSocket)
         * @description A WebSocket endpoint requiring the `operate` permission. The framing
         *     carries the channel: **binary** frames are stdin and the command's raw
         *     output, **text** frames are control messages.
         *
         *     The only control message is a resize: `{"t":"resize","rows":40,"cols":120}`.
         *     When the command exits, the server sends a text `{"t":"exit","exit_code":0}`
         *     frame and closes.
         *
         *     Every exec session is written to the audit log with the command, the
         *     user and the container.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                     *     arrival whether or not the permission check that follows passes, so a
                     *     rejected ticket cannot be retried against another endpoint.
                     */
                    ticket: components["parameters"]["StreamTicket"];
                    /**
                     * @description The command to run, one repeat per argument. Defaults to `/bin/sh`,
                     *     the one shell every image has.
                     */
                    cmd?: string[];
                    /** @description Allocate a pseudo-terminal. */
                    tty?: boolean;
                    /** @description Run as this user, e.g. `root` or `1000:1000`. */
                    user?: string;
                    /** @description Working directory inside the container. */
                    workdir?: string;
                    /** @description Initial terminal height. */
                    rows?: number;
                    /** @description Initial terminal width. */
                    cols?: number;
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching protocols; the exec session follows */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["TicketRejected"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/stats": {
        parameters: {
            query: {
                /**
                 * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                 *     arrival whether or not the permission check that follows passes, so a
                 *     rejected ticket cannot be retried against another endpoint.
                 */
                ticket: components["parameters"]["StreamTicket"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream resource usage for every running container (SSE)
         * @description One `text/event-stream` covering all running containers, each sample
         *     tagged with its container ID. The list view needs a figure per row, and
         *     a browser will not open more than six connections to one origin, so the
         *     daemon fans the per-container engine streams into this one.
         *
         *     The set of containers is re-scanned every 10 seconds, so one that
         *     starts appears within that window and one that stops drops out of it. A
         *     single container failing does not end the stream — only an unreachable
         *     daemon does.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                     *     arrival whether or not the permission check that follows passes, so a
                     *     rejected ticket cannot be retried against another endpoint.
                     */
                    ticket: components["parameters"]["StreamTicket"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["TicketRejected"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/containers/{id}/stats": {
        parameters: {
            query: {
                /**
                 * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                 *     arrival whether or not the permission check that follows passes, so a
                 *     rejected ticket cannot be retried against another endpoint.
                 */
                ticket: components["parameters"]["StreamTicket"];
            };
            header?: never;
            path: {
                /** @description Container ID or name. */
                id: components["parameters"]["ContainerID"];
            };
            cookie?: never;
        };
        /**
         * Stream resource usage (SSE)
         * @description A `text/event-stream` of one sample per second. Event names: `stats`
         *     with a `Stats` payload, `error` with `{code, message}`, and `eof` when
         *     the container stops. A comment line is sent every 25 seconds so an idle
         *     stream is not closed by a proxy.
         *
         *     CPU percentage is computed the way `docker stats` computes it: the
         *     container's CPU delta over the system delta, multiplied by the number
         *     of cores. Memory usage excludes the page cache, so the number matches
         *     what the kernel would reclaim under pressure rather than the raw
         *     cgroup total.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                     *     arrival whether or not the permission check that follows passes, so a
                     *     rejected ticket cannot be retried against another endpoint.
                     */
                    ticket: components["parameters"]["StreamTicket"];
                };
                header?: never;
                path: {
                    /** @description Container ID or name. */
                    id: components["parameters"]["ContainerID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["TicketRejected"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/events": {
        parameters: {
            query: {
                /**
                 * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                 *     arrival whether or not the permission check that follows passes, so a
                 *     rejected ticket cannot be retried against another endpoint.
                 */
                ticket: components["parameters"]["StreamTicket"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Docker engine events (SSE)
         * @description A `text/event-stream` of engine events — containers starting and
         *     dying, images being pulled, volumes and networks changing. The UI uses
         *     it to refresh lists without polling. Event names: `event` with a
         *     `DockerEvent` payload, `error` with `{code, message}`.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
                     *     arrival whether or not the permission check that follows passes, so a
                     *     rejected ticket cannot be retried against another endpoint.
                     */
                    ticket: components["parameters"]["StreamTicket"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["TicketRejected"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List images */
        get: {
            parameters: {
                query?: {
                    /** @description Include intermediate layers. */
                    all?: boolean;
                    /**
                     * @description Tri-state. Absent means no filter; `true` restricts to untagged
                     *     images, `false` to tagged ones.
                     */
                    dangling?: boolean;
                    label?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching images, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Image"][];
                            total: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List volumes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Volumes, sorted by name */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Volume"][];
                            total: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List networks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Networks, sorted by name */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Network"][];
                            total: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["NotInitialized"];
                503: components["responses"]["DockerUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable, machine-readable identifier.
                 * @enum {string}
                 */
                code: "BAD_REQUEST" | "VALIDATION_FAILED" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "CONFLICT" | "RATE_LIMITED" | "PAYLOAD_TOO_LARGE" | "INTERNAL" | "SERVICE_UNAVAILABLE" | "REQUEST_CANCELED" | "NOT_INITIALIZED" | "ALREADY_INITIALIZED" | "INVALID_CREDENTIALS" | "TOKEN_EXPIRED" | "ACCOUNT_DISABLED" | "CSRF_INVALID" | "CONTAINER_NOT_FOUND" | "IMAGE_NOT_FOUND" | "VOLUME_NOT_FOUND" | "NETWORK_NOT_FOUND" | "DOCKER_UNAVAILABLE" | "DOCKER_ERROR";
                /**
                 * @description Human-readable explanation, shown to the operator verbatim.
                 *     For engine failures this is the Docker daemon's own text.
                 */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Credentials: {
            /** @description Case-insensitive; the casing given is preserved for display. */
            username: string;
            /**
             * Format: password
             * @description At least 12 characters and at least two character classes
             *     (lowercase, uppercase, digit, symbol).
             */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        Session: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            /** @description Shown once; only its hash is stored. */
            refresh_token: string;
            /** Format: date-time */
            refresh_expires_at: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        Permission: "read" | "operate" | "create" | "delete" | "build" | "prune" | "privileged" | "admin";
        User: {
            id?: string;
            username?: string;
            /** @enum {string} */
            role?: "admin" | "operator" | "viewer";
            totp_enabled?: boolean;
            disabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_login_at?: string;
            permissions?: components["schemas"]["Permission"][];
        };
        CurrentUser: components["schemas"]["User"] & {
            /** @description Set when the caller authenticated with an API token. */
            token_id?: string;
            scopes?: string[];
        };
        VersionInfo: {
            version?: string;
            commit?: string;
            build_date?: string;
            go_version?: string;
            /** @example linux/amd64 */
            platform?: string;
        };
        EngineStatus: {
            reachable: boolean;
            api_version?: string;
            os_type?: string;
            /** @description Why the daemon could not be reached, when unreachable. */
            error?: string;
        };
        Port: {
            ip?: string;
            private_port?: number;
            public_port?: number;
            /** @example tcp */
            type?: string;
        };
        Container: {
            id?: string;
            name?: string;
            names?: string[];
            image?: string;
            image_id?: string;
            command?: string;
            /** Format: date-time */
            created?: string;
            /** @example running */
            state?: string;
            /** @example Up 2 hours (healthy) */
            status?: string;
            /**
             * @description Parsed out of the status line; empty when no healthcheck.
             * @enum {string}
             */
            health?: "" | "healthy" | "unhealthy" | "starting";
            ports?: components["schemas"]["Port"][];
            labels?: {
                [key: string]: string;
            };
            networks?: string[];
            mounts?: string[];
            /** @description -1 unless `size=true` was requested. */
            size_rw?: number;
            /** @description -1 unless `size=true` was requested. */
            size_root_fs?: number;
        };
        ContainerDetail: components["schemas"]["Container"] & {
            restart_count?: number;
            platform?: string;
            driver?: string;
            log_path?: string;
            path?: string;
            args?: string[];
            entrypoint?: string[];
            cmd?: string[];
            env?: string[];
            working_dir?: string;
            user?: string;
            hostname?: string;
            restart_policy?: string;
            privileged?: boolean;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            exit_code?: number;
            oom_killed?: boolean;
            pid?: number;
            error?: string;
            mount_points?: components["schemas"]["MountPoint"][];
            network_list?: components["schemas"]["NetworkAttachment"][];
            health_check?: {
                status?: string;
                failing_streak?: number;
                last_output?: string;
            };
            port_bindings?: {
                [key: string]: components["schemas"]["Port"][];
            };
        };
        MountPoint: {
            /** @example volume */
            type?: string;
            name?: string;
            source?: string;
            destination?: string;
            driver?: string;
            mode?: string;
            rw?: boolean;
            propagation?: string;
        };
        NetworkAttachment: {
            name?: string;
            network_id?: string;
            endpoint_id?: string;
            ip_address?: string;
            ip_prefix_len?: number;
            gateway?: string;
            mac_address?: string;
            aliases?: string[];
        };
        Image: {
            id?: string;
            parent_id?: string;
            repo_tags?: string[];
            repo_digests?: string[];
            /** Format: date-time */
            created?: string;
            size?: number;
            shared_size?: number;
            labels?: {
                [key: string]: string;
            };
            /** @description Containers using this image, or -1 when not computed. */
            containers?: number;
            dangling?: boolean;
        };
        Volume: {
            name?: string;
            driver?: string;
            mountpoint?: string;
            scope?: string;
            /** Format: date-time */
            created_at?: string;
            labels?: {
                [key: string]: string;
            };
            options?: {
                [key: string]: string;
            };
            /** @description -1 when the engine did not report usage data. */
            size?: number;
            /** @description -1 when the engine did not report usage data. */
            ref_count?: number;
        };
        Network: {
            id?: string;
            name?: string;
            driver?: string;
            scope?: string;
            /** Format: date-time */
            created?: string;
            internal?: boolean;
            attachable?: boolean;
            ingress?: boolean;
            enable_ipv6?: boolean;
            ipam?: {
                subnet?: string;
                gateway?: string;
                ip_range?: string;
                aux_address?: string;
            }[];
            labels?: {
                [key: string]: string;
            };
            container_count?: number;
        };
        SystemInfo: {
            server_version?: string;
            api_version?: string;
            name?: string;
            os_type?: string;
            operating_system?: string;
            architecture?: string;
            kernel_version?: string;
            ncpu?: number;
            mem_total?: number;
            docker_root_dir?: string;
            storage_driver?: string;
            logging_driver?: string;
            cgroup_driver?: string;
            containers?: number;
            containers_running?: number;
            containers_paused?: number;
            containers_stopped?: number;
            images?: number;
            warnings?: string[];
        };
        DiskUsageEntry: {
            count?: number;
            size?: number;
            reclaimable?: number;
        };
        DiskUsage: {
            layers_size?: number;
            images?: components["schemas"]["DiskUsageEntry"];
            containers?: components["schemas"]["DiskUsageEntry"];
            volumes?: components["schemas"]["DiskUsageEntry"];
            build_cache?: components["schemas"]["DiskUsageEntry"];
        };
        BatchRequest: {
            /** @description Container IDs or names. */
            ids: string[];
            /**
             * @description The action to apply to each container. `remove` forces removal of
             *     running containers, because a bulk remove that stopped at the first
             *     running container would be worse than useless.
             * @enum {string}
             */
            action: "start" | "stop" | "restart" | "pause" | "unpause" | "kill" | "remove";
        };
        BatchResult: {
            id: string;
            ok: boolean;
            /** @description Present only when `ok` is false. */
            error?: string;
            /**
             * @description The stable error code for this container's failure.
             * @example CONTAINER_NOT_FOUND
             */
            code?: string;
        };
        BatchResponse: {
            action: string;
            total: number;
            succeeded: number;
            failed: number;
            results: components["schemas"]["BatchResult"][];
        };
        RedeployResult: {
            /** @description The container that was replaced. */
            old_id: string;
            /**
             * @description The container now running. Equal to `old_id` when `rolled_back` is
             *     true, because nothing replaced it.
             */
            new_id: string;
            /** @description The image tag that was pulled and deployed. */
            image: string;
            /**
             * @description True when the new container could not be created or started and the
             *     original was restored under its own name.
             */
            rolled_back: boolean;
        };
        /** @description One sample from the stats stream, taken once a second. */
        Stats: {
            /** Format: date-time */
            timestamp: string;
            /**
             * Format: double
             * @description Percent of one host CPU, so a container using two cores fully reads
             *     200 on a machine with two or more.
             */
            cpu_percent: number;
            /**
             * Format: int64
             * @description Bytes in use, excluding the reclaimable page cache.
             */
            memory_usage: number;
            /** Format: int64 */
            memory_limit: number;
            /** Format: double */
            memory_percent: number;
            /**
             * Format: int64
             * @description Cumulative bytes received across every interface.
             */
            network_rx: number;
            /** Format: int64 */
            network_tx: number;
            /**
             * Format: int64
             * @description Cumulative bytes read from block devices.
             */
            block_read: number;
            /** Format: int64 */
            block_write: number;
            pids: number;
        };
        /** @description One JSON text frame on the log WebSocket. */
        LogFrame: {
            /** @enum {string} */
            t: "log" | "err" | "eof" | "exit";
            /**
             * @description Present on `log` frames.
             * @enum {string}
             */
            s?: "stdout" | "stderr";
            /**
             * Format: date-time
             * @description Present when `timestamps=true` was requested.
             */
            ts?: string;
            /** @description The line, or the failure message on an `err` frame. */
            m?: string;
            /** @description The stable error code, on an `err` frame. */
            code?: string;
            /** @description The command's status, on an `exit` frame from exec. */
            exit_code?: number;
        };
        /** @description One engine event from the SSE event stream. */
        DockerEvent: {
            /**
             * @description The object kind the event concerns.
             * @example container
             */
            type: string;
            /** @example start */
            action: string;
            /** @description The object's ID. */
            actor: string;
            /** @description The object's name, when the engine reports one. */
            name?: string;
            scope?: string;
            attributes?: {
                [key: string]: string;
            };
            /** Format: date-time */
            time: string;
        };
        /**
         * @description One sample from `/containers/stats`: the same fields as `Stats`, plus
         *     the container the sample belongs to.
         */
        IdentifiedStats: {
            id: string;
        } & components["schemas"]["Stats"];
    };
    responses: {
        /** @description The lifecycle action was applied */
        ActionResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    id: string;
                    /** @enum {string} */
                    action: "start" | "stop" | "restart" | "pause" | "unpause" | "kill" | "rename";
                    /** @enum {string} */
                    status: "ok";
                };
            };
        };
        /**
         * @description The ticket was missing, already used, or older than 60 seconds. Fetch a
         *     fresh one and reconnect.
         */
        TicketRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "a valid streaming ticket is required; request one from POST /api/v1/auth/ws-ticket"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid credential was presented */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "authentication required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The caller's role lacks the permission this route requires. `details`
         *     names the role and the missing permission.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "role \"viewer\" may not operate",
                 *         "details": {
                 *           "role": "viewer",
                 *           "required_permission": "operate"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The installation has no admin account yet */
        NotInitialized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Two distinct situations share this status, told apart by `code`:
         *     `NOT_INITIALIZED` means the installation has no admin account yet, and
         *     `CONFLICT` means the engine refused the operation given the container's
         *     current state (removing a running container without `force`, say). The
         *     engine's own guidance is passed through in `message`.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body failed validation */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests; `Retry-After` says when to try again */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A query parameter was malformed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such container */
        ContainerNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "CONTAINER_NOT_FOUND",
                 *         "message": "no such container: abc"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The Docker daemon could not be reached. iskeled keeps serving so the
         *     operator can see the problem; the message names the endpoint and the
         *     most likely fix.
         */
        DockerUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "DOCKER_UNAVAILABLE",
                 *         "message": "cannot reach the Docker daemon at unix:///var/run/docker.sock"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Container ID or name. */
        ContainerID: string;
        /**
         * @description Seconds to wait before the engine sends SIGKILL. Omitted means the
         *     engine's own default (10s).
         */
        StopTimeout: number;
        /**
         * @description A single-use ticket from `POST /auth/ws-ticket`. It is consumed on
         *     arrival whether or not the permission check that follows passes, so a
         *     rejected ticket cannot be retried against another endpoint.
         */
        StreamTicket: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
